service: DownloadThisVideo

provider:
  name: aws
  runtime: nodejs8.10
  stage: beta
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - ${self:custom.snsArn}
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource:
        - "*"

  environment:
    TWITTER_CONSUMER_KEY:
    TWITTER_CONSUMER_SECRET:
    TWITTER_ACCESS_TOKEN:
    TWITTER_ACCESS_TOKEN_SECRET:
    REDIS_HOSTNAME:
    REDIS_PORT:
    REDIS_PASSWORD:
    TWITTER_SCREEN_NAME: this_vid
    TOPIC_ARN: ${self:custom.snsArn}
functions:
  fetchTweetsToDownload:
    handler: handler.fetchTweetsToDownload
    events:
      - schedule: rate(5 minutes)
  retryFailedTasks:
    handler: handler.retryFailedTasks
  sendDownloadLink:
    handler: handler.sendDownloadLink
    events:
      - sns: newMention

custom:
  snsArn: "arn:aws:sns:us-east-1:<AccountId>:newMention"
