service: DownloadThisVideo
plugins:
- serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: beta
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - "Fn::Join":
          - ':'
          - - "arn:aws:sns:us-east-1"
            - Ref: AWS::AccountId
            - "newMention"
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource:
        - "*"

  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    REDIS_HOSTNAME: ${env:REDIS_HOSTNAME}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    TWITTER_SCREEN_NAME: ${env:TWITTER_SCREEN_NAME}
    EXTERNAL_URL: ${env:EXTERNAL_URL}
    TOPIC_ARN:
      "Fn::Join":
      - ':'
      -
        - "arn:aws:sns:us-east-1"
        - Ref: AWS::AccountId
        - "newMention"

package:
  include:
  - views/**
  exclude:
  - README.md
  - .gitignore
  - .env
  - .env.example
  - .idea/**
  - .git/**
  - this-vid.png

functions:
  fetchTweetsToDownload:
    handler: handler.fetchTweetsToDownload
    events:
    - schedule: rate(4 minutes)
  retryFailedTasks:
    handler: handler.retryFailedTasks
  sendDownloadLink:
    handler: handler.sendDownloadLink
    events:
    - sns: newMention
  getDownloads:
    handler: handler.getDownloads
    events:
    - http:
        path: /{username}
        method: get
        request:
          parameters:
            paths:
              username: true
  getHomePage:
    handler: handler.getHomePage
    events:
    - http:
        path: /
        method: get
