service: DownloadThisVideo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: beta
  memorySize: 128

  environment:
    TWITTER_CONSUMER_KEY:
    TWITTER_CONSUMER_SECRET:
    TWITTER_ACCESS_TOKEN:
    TWITTER_ACCESS_TOKEN_SECRET:
    REDIS_HOSTNAME:
    REDIS_PORT:
    REDIS_PASSWORD:
    TWITTER_SCREEN_NAME:

functions:
  fetchTweetsToDownload:
    handler: handler.fetchTweetsToDownload
    events:
      - schedule: rate(10 minutes)
  sendDownloadLinks:
    handler: handler.sendDownloadLinks
    events:
      - schedule: rate(10 minutes)
